### ISSUE TITLE
MPU9250 connection failed

### ISSUE THREAD

**Issue by jonathanrjpereira** [Snowda/MPU9250#7]
Initializing I2C devices...
Testing device connections...
MPU9250 connection failed

Could you specify the connections for the Arduino UNO & also any changes in the code for the Arduino UNO? Could this be a result of not using external pull-up resistors for the I2C lines?

**Comment by Aiduss** [comment]
Same here. I have different default MPU9250 adress @ 0x69 and i just can't get it work with default code.
