### ISSUE TITLE
Printing Values even when Connection Failed

### ISSUE THREAD

**Issue by jonathanrjpereira** [Snowda/MPU9250#8]
```
Initializing I2C devices...
Testing device connections...
MPU9250 connection failed
a/g/m:	0	0	0	0	0	0	0	0	0
a/g/m:	0	0	0	0	0	0	0	0	0
a/g/m:	0	0	0	0	0	0	0	0	0
a/g/m:	0	0	0	0	0	0	0	0	0
```

I observed that I got a Connection failed error.  But the code still prints the values for each sensor as 0. Instead, shouldn't there be no values are printed whatsoever & only the error message be printed?
I think I can solve this error and push the code.

**Comment by Bharatmodugu** [comment]
Hi jonathanrjpereira,
I too am facing the same issue. If you have solved the error, please upload the corrected code. My E-Mail ID is bharatkumar1357@gmail.com. I need it urgently,
![com](https://user-images.githubusercontent.com/41162484/42643694-6d27296a-8617-11e8-8bc2-a35e8ef1c535.JPG)

**Comment by jonathanrjpereira** [comment]
Try using the sensor with a breadboard. I did this and it worked.

**Comment by jayaramanrp** [comment]
jonathanrjpereira,
I'm facing the same issue. 
could please share the schematics.

**Comment by jonathanrjpereira** [comment]
In my case this was caused due to loose connections between the sensor module & Arduino. So instead I minimised the use of jumper cables with the help of a breadboard. This solved the issue for me.
@Bharatmodugu @jayaramanrp
